### ISSUE TITLE
Proposal: module definition API

### ISSUE THREAD

**Issue by eric-brechemier** [getify/h5ive-DEPRECATED#1]
I defined an abstraction layer for module definition:
https://github.com/eric-brechemier/scopeornot

I propose to contribute this API to the H5api project.

In its simplest form, it is a replacement for the JavaScript Module Pattern:

```
scope(function(){
  // my module
});
```

With additional parameters, dependencies and asynchronous loading can be managed as well:

```
scope(function(context){
  // dependencies are loaded as properties in context object
},["need1","need2"],"myModule");
```

I have used this API successfully for static and dynamic loading of modules, in the browser and other environments.

Here is a presentation I made at ParisJS back in December:
http://www.slideshare.net/ericbrechemier/scope-or-not

**Comment by getify** [comment]
Eric-
I appreciate the suggestion. It is, in my opinion, too early in the project to start making decisions about how things will be packaged and built. I'm sure the community will insist on AMD format, but I want to resist such details while we're still actively developing.

I would like to have a build tool that allows the dev to choose which "format" they want, and to build in which modules they need, etc. The core lib and modules should be "module format" agnostic, IMHO.

But I'll keep this issue open and we'll revisit these details as we get closer to getting something that's usable for real.

Thanks for the contribution suggestion! :)

**Comment by eric-brechemier** [comment]
Kyle, I think that you missed the scope, no pun intended, of my proposal  :)

scope() is an API designed to be 100% compatible with AMD (same 3 arguments, reverse order) while removing all the semantic attached to AMD to provide compatibility with any other (present and future) loading mechanism including static definitions.

My idea was to include this API definition in H5api, while your comments seem related to using it as part of the code of H5api if I understand correctly.

**Comment by getify** [comment]
Yes, Eric, it appears I did misunderstand the point of your suggestion.

However, with that clarifying point, I feel it's even less likely that what you're suggesting fits well in _this_ project. The goal of this project is not to create a generic framework (there are tons out there for that). We're not going to create class/inheritance stuff, we're not doing event handling or anything like that, DOM manip, etc.

This project is **only** for wrapping existing native HTML5 JavaScript APIs in thin facades.

Since "modules" and "module loading" are not native HTML5 APIs, putting something into `H5api` to provide users that general ability is not appropriate.

Now, ES6 is going to have its own modules, and maybe there will eventually need to be some sort of wrappers for that stuff. But _this_ project is only focusing on what's currently in HTML5 and trying to wrap it.

I appreciate the idea and participation though. :)

**Comment by eric-brechemier** [comment]
OK, just let me know when you start ES6api ;)

**Comment by nathaniellee** [comment]
No event handling? Hmm... event handling has been such a key part of HTML5 video in the projects I've been on at work for the past year...

**Comment by getify** [comment]
@nathaniellee 

OK, that's a good point... I didn't mean there wouldn't be event handling at all. I meant we wouldn't be providing a custom event handling interface. Obviously each API will have events that you need to listen for (look at XHR already, for instance). I just meant I was't going to put a stand-alone "do your own events" interface into HTML5, because it was outside the scope of thinly wrapping existing HTML5 APIs.

That having been said, I suppose it's possible we might thinly wrap `addEventListener` or something like that, but it's certainly not something I was planning on doing.
